baseURL = "https://black-mud-0b39c7503.azurestaticapps.net/"
languageCode = "en-us"
title = "I am Josef Fürlinger"
theme = "anatole"

[params]
author = "Josef Fürlinger"
description = "Call me Joe"
profilePicture = "images/profile.jpg"
mainSections = ["posts"]
displayMode = "dark"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/josef-f%C3%BCrlinger-417ba025"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jfuerlinger/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/joefuerlinger/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:josef.fuerlinger@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
